
---

defaults: &defaults
  piki:
    path: '/home/www/git/piki.git'
    url: 'piki'
    read:  :org
    bare: true
    update:  :org
    update:  :org
    ext: '.wiki'
    help_link: 'wiki/tep/doc/wiki#start'
  main:
    path: '/home/www/git/web.git'
    bare: true
    #url: 'web'
    url: ''
    branch: edit
    read:  :anon
    ext: '.wiki'
    help_link: 'wiki/tep/doc/wiki#start'
  web_edit:
    path: '/home/www/git/web.git'
    bare: true
    url: 'webed'
    branch: edit
    read:  :org
    update:  :org
    #nogit: true
    ext: '.wiki'
    help_link: '/wiki/tep/doc/wiki#start'


local: &local
  <<: *defaults
  piki:
    path: '/home/vitas/git/piki'
    url: 'piki'
    read:  :org
    bare: false
    update:  :org
    update:  :org
    help_link: 'wiki/tep/doc/wiki#start'
    ext: '.wiki'
  main:
    path: '/home/vitas/git/web'
    bare: false
    branch: edit
    #url: 'web'
    url: ''
    read:  :anon
    update:  :org
    #nogit: true
    ext: '.wiki'
  web_edit:
    path: '/home/vitas/git/web'
    bare: true
    url: 'webed'
    branch: edit
    read:  :org
    update:  :org
    #nogit: true
    ext: '.wiki'
  webfs:
    url: 'webfs'
    path: '/home/vitas/tmp/pikoweb/web'
    #bare: true
    #branch: edit
    read:  :org
    update:  :org
    nogit: true
    ext: '.wiki'

test:
  <<: *local

development:
  <<: *defaults

production:
  <<: *defaults
