---

defaults: &defaults
  piki:
    path: '/home/www/git/piki.git'
    url: 'piki'
    bare: true
    templates: 'tepmac'
    ext: '.wiki'
    help_link: 'wiki/tep/doc/wiki#start'
    read:   :org
    update: :org
  tepmac:
    path: '/home/www/git/tepmac.git'
    url: 'tepmac'
    templates: 'tepmac'
    bare: true
    ext: '.wiki'
    help_link: 'wiki/tep/doc/wiki#start'
    read:   :org
    update: :morg
  main:
    path: '/home/www/git/web.git'
    bare: true
    #url: 'web'
    url: ''
    branch: master
    ext: '.wiki'
    help_link: 'wiki/tep/doc/wiki#start'
    templates: 'tepmac'
    read:  :anon
    update: NULL
  web_edit:
    path: '/home/www/git/web.git'
    templates: 'tepmac'
    bare: true
    url: 'webed'
    branch: master
    #nogit: true
    ext: '.wiki'
    help_link: '/wiki/tep/doc/wiki#start'
    read:   :org
    update: :morg
  wikuk:
    url: 'wikuk'
    templates: 'tepmac'
    path: '/home/pikomat/wikuk'
    nogit: true
    ext: '.wiki'
    read:   :org
    update: :org

local: &local
  <<: *defaults
  piki:
    path: '/home/vitas/git/piki'
    url: 'piki'
    read:  :org
    templates: 'tepmac'
    bare: false
    help_link: 'wiki/tep/doc/wiki#start'
    ext: '.wiki'
    update: :org
    update: :org
  wikuk:
    url: 'wikuk'
    templates: 'tepmac'
    path: '/home/vitas/tmp/wikuk'
    nogit: true
    ext: '.wiki'
    read:   :org
    update: :org
  tepmac:
    path: '/home/vitas/git/tepmac'
    url: 'tepmac'
    templates: 'tepmac'
    bare: false
    help_link: 'wiki/tep/doc/wiki#start'
    ext: '.wiki'
    read:   :org
    update: :morg
  main:
    path: '/home/vitas/git/web'
    bare: false
    branch: master
    templates: 'tepmac'
    url: ''
    ext: '.wiki'
    read:   :anon
    update: :org
  web_edit:
    path: '/home/vitas/git/web'
    bare: true
    templates: 'tepmac'
    url: 'webed'
    branch: master
    read:    :org
    update:  :morg
    ext: '.wiki'

test:
  <<: *local

development:
  <<: *defaults

production:
  <<: *defaults
