
---

defaults: &defaults
  main:
    path: '/home/vitas/tmp/piki'
    url: 'wiki'
    read:  :org
    update:  :org


  read:
    path: '/home/vitas/tmp/piki'
    url: 'read'
    read:  :anon
    #update:  :org

test:
  <<: *defaults
production:
  <<: *defaults
development:
  <<: *defaults
  web:
    path: '/home/vitas/tmp/pikoweb'
    url: 'web'
    read:  :org
    update:  :org
    nogit: true
    ext: '.wiki'
